version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing AWS CLI..."
      - npm install -g aws-cli
  pre_build:
    commands:
      - echo "Pre-build step..."
  build:
    commands:
      - echo "Build step not required for static websites..."
  post_build:
    commands:
      - echo "Copying files to the S3 bucket..."
      - aws s3 sync . http://akinyolcicom.s3-website-us-east-1.amazonaws.com --delete
